//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibraryProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookLocation
    {
        public int Id { get; set; }
        public int Room { get; set; }
        public string Place { get; set; }
        public bool IsTaken { get; set; }
    
        public virtual Reader Reader { get; set; }
        public virtual Publication Publication { get; set; }
    }
}
